name: Update README Badge

on:
  push:
    branches:
      - master

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count completed tasks
        id: count-tasks
        run: |
          # Count the number of '✅' in the README file
          count=$(grep -oP '(?<=<td align="center">)✅(?=</td>)' README.md | wc -l)
          echo "TASK_COUNT=$count" >> $GITHUB_ENV

      - name: Update README with dynamic badge
        run: |
          # Update the README file to include the dynamic badge with the current task count
          badge_url="https://img.shields.io/badge/Progress-${TASK_COUNT}%2F150-0078D4"
          sed -i "s|https://img.shields.io/badge/Progress-[0-9]*%2F150-0078D4|$badge_url|g" README.md

      - name: Commit and push changes
        run: |
          if ! git diff --exit-code README.md > /dev/null; then
            git config --global user.email "actions@github.com"
            git config --global user.name "Github Actions"
            git add README.md
            git commit -m "Update README badge with progress: $TASK_COUNT/150"
            git push
          fi

